pipeline {
  agent any
  stages {
    stage('Test') {
      agent {
        docker { 
          image 'ubuntu:20.04' 
        }
      }
      steps {
        sh 'apt-get update && apt-get install -y nodejs npm && node --version'
      }
    }
  }
}
